export interface CategoryInfo {
  subcategory: string;
  category: string;
}

export const CATEGORY_MAPPING: Record<string, CategoryInfo> = {
  // 1.1 - RECEITA BRUTA
  "RECEITA COM SERVIÇO NACIONAL": { subcategory: "1.1.1 - RECEITA BRUTA", category: "1.1 - RECEITA BRUTA" },
  "RECEITAS COM SERVIÇO NACIONAL": { subcategory: "1.1.1 - RECEITA BRUTA", category: "1.1 - RECEITA BRUTA" },
  "RECEITA COM CARGA E DESCARGA": { subcategory: "1.1.1 - RECEITA BRUTA", category: "1.1 - RECEITA BRUTA" },
  "RECEITA NOTA DE DÉBITO": { subcategory: "1.1.1 - RECEITA BRUTA", category: "1.1 - RECEITA BRUTA" },
  "DESCONTOS S/ PRESTAÇÃO DE SERVIÇOS DE TRANSPORTES": { subcategory: "1.1.1 - RECEITA BRUTA", category: "1.1 - RECEITA BRUTA" },

  // 2.1 - CUSTOS OPERACIONAIS
  "ABASTECIMENTO EXTERNO": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ADIANTAMENTO CONVÊNIO - ALELO": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "DIESEL EXTERNO": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "DIESEL INTERNO": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ARLA": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ALCOOL E GASOLINA OPERACIONAL": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "COMBUSTÍVEIS - ADM": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "GLP - GAS DE EMPILHADEIRA": { subcategory: "2.1.1 - COMBUSTÍVEL", category: "2.1 - CUSTOS OPERACIONAIS" },
  "PEDÁGIO": { subcategory: "2.1.2 - PEDÁGIO", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ADIANTAMENTO P/AGREGADOS": { subcategory: "2.1.3 - AGREGADOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "Carreteiros pessoa física": { subcategory: "2.1.3 - TERCEIROS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "Carreteiros pessoa jurídica": { subcategory: "2.1.3 - TERCEIROS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "FRETE TERCEIROS PF": { subcategory: "2.1.3 - TERCEIROS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "FRETE TERCEIROS PJ": { subcategory: "2.1.3 - TERCEIROS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ESCOLTA": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "GERENCIAMENTO DE RISCOS": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "RASTREAMENTO": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "MONITORAMENTO": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SERVIÇOS EM EQUIP. MONITORAMENTO E RASTREAMENTO": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SEGUROS EM EQUP. MONITORAMENTO E RASTREAMENTO": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "RECEBIMENTO DE SINISTROS": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SEGURO DE CARGA": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SINISTROS E AVARIAS DE CARGAS": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SEGUROS": { subcategory: "2.1.4 - GR", category: "2.1 - CUSTOS OPERACIONAIS" },
  "Licença de Rodagem Estadual": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "Licença de Rodagem Federal": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "EQUIPAMENTOS DE SEGURANÇA": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SEGURO DE VEÍCULOS": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "IPVA": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "LICENCIAMENTO": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "MULTAS DE TRÂNSITO": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "MATERIAIS DE SEGURANÇA": { subcategory: "2.1.5 - FROTA", category: "2.1 - CUSTOS OPERACIONAIS" },
  "COMISSÕES CLIENTES": { subcategory: "2.1.6 - COMISSÕES", category: "2.1 - CUSTOS OPERACIONAIS" },
  "DESPESAS C/ENTREGAS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "DESPESAS OPERACIONAIS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "MATERIAL DE APOIO DE CARGA": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "TAXAS ADMINISTRATIVAS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "TAXAS E LICENÇAS DE TRANSPORTE": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "TAXAS MUNICIPAIS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "TAXAS ESTADUAIS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "TICKET REEMBOLSO DE REFEIÇÃO": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ALUGUEL DE EQUIPAMENTOS OPERACIONAIS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "CARGA E DESCARGA PF": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "DESPESAS PORTUÁRIAS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "EQUIPAMENTOS E ACESSÓRIOS OPERACIONAIS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "ARMAZENAGEM": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "CUSTO DOS SERVIÇOS PRESTADOS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "CONFERENTE": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "MOTORISTAS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "PERDAS OPERACIONAIS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "SERVIÇOS PERICIAIS, LAUDO, EXAMES TECNIC": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "REEMBOLSO DE DESLOCAMENTO": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },
  "OUTROS IMPOSTOS E TAXAS": { subcategory: "2.1.7 - CUSTOS DIVERSOS", category: "2.1 - CUSTOS OPERACIONAIS" },

  // 2.2 - DESPESA ADMINISTRATIVA
  "HOSPEDAGEM": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "LICENÇA E FUNCIONAMENTO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "LICENÇA DE SOFTWARE": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "COMISSÕES DE TRANSPORTES": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "HONORÁRIOS CONTÁBEIS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "LOCAÇÃO DE EQUIPAMENTOS ADM": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "CORREIOS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "CUSTAS PROCESSUAIS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "DESPESAS C/CARTÓRIO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "DESPESAS C/CERTIFICADOS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "DESPESAS C/DESPACHANTE": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "ESTACIONAMENTO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "IMPRESSOS E FORMULÁRIOS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "INDENIZAÇÕES PROCESSUAIS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MANUTENÇÃO EQPTOS DE COMUNICAÇÃO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "PRESTAÇÃO DE SERVIÇO DE INFORMÁTICA": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MATERIAIS DE ESCRITÓRIO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MATERIAIS DE LIMPEZA": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MATERIAIS DE USO E CONSUMO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MOTOBOY": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "COPA E COZINHA": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "EVENTOS E CONFRATERNIZAÇÕES": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "BENS DE PEQUENO VALOR": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "HONORÁRIOS JURÍDICOS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "LINKS E PROVEDORES DE INTERNET": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MANUTENÇÃO DE SOFTWARE": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "SUPRIMENTOS INFORMÁTICA": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "VIAGENS E FUNCIONAMENTO": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "MULTAS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "ASSESSORIA COMERCIAL": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "CRACHÁS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "DESPACHANTE": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "DESPESAS COM MOVEIS E UTENSILIOS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "FARMACEUTICA": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },
  "OUTRAS DESPESAS COMERCIAIS": { subcategory: "2.2.1 - DESPESA ADMINISTRATIVA", category: "2.2 - DESPESA ADMINISTRATIVA" },

  // 2.3 - FOLHA DE PAGAMENTO
  "ADIANTAMENTO À FUNCIONÁRIOS": { subcategory: "2.3.1 - SALÁRIO", category: "2.3 - FOLHA DE PAGAMENTO" },
  "ADIANTAMENTO FÉRIAS FUNCIONÁRIOS": { subcategory: "2.3.1 - SALÁRIO", category: "2.3 - FOLHA DE PAGAMENTO" },
  "SALÁRIOS A PAGAR": { subcategory: "2.3.1 - SALÁRIO", category: "2.3 - FOLHA DE PAGAMENTO" },
  "13º SALÁRIO": { subcategory: "2.3.1 - SALÁRIO", category: "2.3 - FOLHA DE PAGAMENTO" },
  "13º SALÁRIO A PAGAR": { subcategory: "2.3.1 - SALÁRIO", category: "2.3 - FOLHA DE PAGAMENTO" },
  "INSS A RECOLHER": { subcategory: "2.3.2 - ENCARGOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "FGTS A RECOLHER": { subcategory: "2.3.2 - ENCARGOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "IRRF S/FOLHA DE PAGTO": { subcategory: "2.3.2 - ENCARGOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "FGTS RESCISÓRIO": { subcategory: "2.3.2 - ENCARGOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "ASSISTÊNCIA ODONTOLOGICA": { subcategory: "2.3.3 - BENEFICIOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "ASSISTENCIA ODONTOLOGICA": { subcategory: "2.3.3 - BENEFICIOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "CURSOS E TREINAMENTO DE FUNCIONARIOS": { subcategory: "2.3.3 - BENEFICIOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "DESPESAS MEDICAS EXTRA PLANO DE SAUDE": { subcategory: "2.3.3 - BENEFICIOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "SEGURO DE VIDA": { subcategory: "2.3.3 - BENEFICIOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "VALE TRANSPORTE": { subcategory: "2.3.3 - BENEFICIOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "COMISSÕES": { subcategory: "2.3.4 - COMISSÕES", category: "2.3 - FOLHA DE PAGAMENTO" },
  "BRINDES": { subcategory: "2.3.4 - COMISSÕES", category: "2.3 - FOLHA DE PAGAMENTO" },
  "PREMIO": { subcategory: "2.3.4 - COMISSÕES", category: "2.3 - FOLHA DE PAGAMENTO" },
  "EPI - EQPTO DE SEGURANCA DO TRABALHO": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "PENSÃO ALIMENTÍCIA A PAGAR": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "EMPRESTIMO EM FOLHA": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "RESCISÕES A PAGAR": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "TAXA SECURITÁRIA": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "CUSTO DE SERVIÇOS PRESTADOS - FOPAG": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "CONTRIBUIÇÕES SINDICAIS E ASSOCIAÇÕES": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "EPI - EQPTO DE SEGURANÇA DO TRABALHO": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "EXAME OCUPACIONAL": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "UNIFORME": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },
  "MENSALIDADE SINDICAL": { subcategory: "2.3.5 - DIVERSOS", category: "2.3 - FOLHA DE PAGAMENTO" },

  // 2.4 - MANUTENÇÃO
  "MANUTENÇÃO DE EQUIP. E ACESSÓRIOS OPERACIONAIS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE FUNILARIA E PINTURA": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE LAVAGEM DE VEÍCULOS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "TROCA DE OLEO / LUBRIFICANTES": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE DEDETIZAÇÃO": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE ELETRICA": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE MECANICA": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE REFORMA DE BANCOS E ESTOFADOS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE EMBREAGEM": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE FREIO": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE AFERIÇÃO": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE PERSONALIZAÇÃO E ADESIVAGEM": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "SERVIÇOS DE RECONDICIONAMENTO DE PEÇAS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "ALINHAMENTO E BALANCEAMENTO": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "PNEUS - RECAUCHUTAGEM": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "PNEUS - RECAPAGEM": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "PNEUS - SERVIÇOS DE BORRACHARIA (REMENDO, TROCA, RODIZIO)": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "MANUTENÇÃO DE EQUIP E ACESSÓRIOS OPERACIONAIS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "MANUTENÇÃO E REPAROS ADMINISTRATIVOS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "MANUTENÇÃO E AQUISIÇÃO DE MAQUINAS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "MONTAGENS, DESMONTAGENS E CONSERTOS - PNEUS": { subcategory: "2.4.1 - SERVIÇOS", category: "2.4 - MANUTENÇÃO" },
  "PEÇAS E ACESSÓRIOS": { subcategory: "2.4.2 - MATERIAL", category: "2.4 - MANUTENÇÃO" },
  "PEÇAS E ACESSÓRIOS - FROTA": { subcategory: "2.4.2 - MATERIAL", category: "2.4 - MANUTENÇÃO" },
  "PNEUS - AQUISIÇÃO NOVOS": { subcategory: "2.4.2 - MATERIAL", category: "2.4 - MANUTENÇÃO" },

  // 2.5 - OCUPAÇÃO
  "ALUGUEL DE IMÓVEL PJ": { subcategory: "2.5.1 - ALUGUEL", category: "2.5 - OCUPAÇÃO" },
  "AGUA E ESGOTO": { subcategory: "2.5.2 - CONTAS", category: "2.5 - OCUPAÇÃO" },
  "ENERGIA ELÉTRICA": { subcategory: "2.5.2 - CONTAS", category: "2.5 - OCUPAÇÃO" },
  "TELEFONE - FIXA": { subcategory: "2.5.2 - CONTAS", category: "2.5 - OCUPAÇÃO" },
  "TELEFONIA MOVEL": { subcategory: "2.5.2 - CONTAS", category: "2.5 - OCUPAÇÃO" },
  "IPTU": { subcategory: "2.5.2 - CONTAS", category: "2.5 - OCUPAÇÃO" },
  "CONSTRUÇÕES": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },
  "MANUTENÇÃO PREDIAL": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },
  "BENFEITORIAS - TERCEIROS": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },
  "MATERIAIS DE MANUTENÇÃO E CONSERVAÇÃO": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },
  "LICENÇA E FUNCIONAMENTO - ALVARA": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },
  "OUTROS CUSTOS DE SERVIÇOS": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },
  "SEGURANÇA PATRIMONIAL": { subcategory: "2.5.3 - OUTROS", category: "2.5 - OCUPAÇÃO" },

  // 2.6 - OUTRAS RECEITAS
  "OUTRAS RECEITAS": { subcategory: "2.6.6 - OUTRAS RECEITAS", category: "2.6 - OUTRAS RECEITAS" },

  // 2.7 - REC./DESP. FINANCEIRA
  "JUROS PAGOS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "DESCONTOS CONCEDIDOS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "IOF": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "JUROS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "TARIFAS E SERVIÇOS BANCÁRIOS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "TARIFA DESCONTO DE DUPLICATA": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "MULTA S/ TRIBUTOS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "JUROS A APROPRIAR - PARCELAMENTO": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "SINISTROS DE VEICULOS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "FUNDO DE RESERVA - CONSÓRCIO": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "SEGUROS A APROPRIAR (FROTA)": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "JUROS A APROPRIAR - EMPRÉSTIMOS": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },
  "ADIANTAMENTO DE CLIENTES": { subcategory: "2.7.7 - REC./DESP. FINANCEIRA", category: "2.7 - REC./DESP. FINANCEIRA" },

  // 3.1 - IMPOSTOS S/FATURAMENTO
  "PIS A RECOLHER": { subcategory: "3.1.1 - IMPOSTOS S/FATURAMENTO", category: "3.1 - IMPOSTOS S/FATURAMENTO" },
  "COFINS A RECOLHER": { subcategory: "3.1.1 - IMPOSTOS S/FATURAMENTO", category: "3.1 - IMPOSTOS S/FATURAMENTO" },
  "ICMS A RECOLHER": { subcategory: "3.1.1 - IMPOSTOS S/FATURAMENTO", category: "3.1 - IMPOSTOS S/FATURAMENTO" },
  "CPRB A PAGAR": { subcategory: "3.1.1 - IMPOSTOS S/FATURAMENTO", category: "3.1 - IMPOSTOS S/FATURAMENTO" },
  "SIMPLES NACIONAL - DAS": { subcategory: "3.1.1 - IMPOSTOS S/FATURAMENTO", category: "3.1 - IMPOSTOS S/FATURAMENTO" },
  "ISS A RECOLHER": { subcategory: "3.1.1 - IMPOSTOS S/FATURAMENTO", category: "3.1 - IMPOSTOS S/FATURAMENTO" },

  // 4.1 - INVESTIMENTOS
  "INSTALAÇÕES": { subcategory: "4.1.1 - INVESTIMENTOS", category: "4.1 - INVESTIMENTOS" },
  "MÁQUINAS E EQUIPAMENTOS": { subcategory: "4.1.1 - INVESTIMENTOS", category: "4.1 - INVESTIMENTOS" },
  "MÓVEIS E UTENSÍLIOS": { subcategory: "4.1.1 - INVESTIMENTOS", category: "4.1 - INVESTIMENTOS" },
  "EQUIPAMENTOS DE INFORMÁTICA": { subcategory: "4.1.1 - INVESTIMENTOS", category: "4.1 - INVESTIMENTOS" },

  // 4.2 - FINANCIAMENTOS
  "FINANCIAMENTOS": { subcategory: "4.2.2 - FINANCIAMENTOS", category: "4.2 - FINANCIAMENTOS" },

  // 4.3 - CONSORCIOS
  "CONSÓRCIO": { subcategory: "4.3.3 - CONSORCIOS", category: "4.3 - CONSORCIOS" },
  "CONSÓRCIO A PAGAR - CP": { subcategory: "4.3.3 - CONSORCIOS", category: "4.3 - CONSORCIOS" },

  // 4.4 - VENDA DE ATIVO
  "VENDA DE ATIVO IMOBILIZADO": { subcategory: "4.4.4 - VENDA DE ATIVO", category: "4.4 - VENDA DE ATIVO" },

  // 5.1 - EMPRÉSTIMOS
  "EMPRÉSTIMOS": { subcategory: "5.1.1 - EMPRÉSTIMOS", category: "5.1 - EMPRÉSTIMOS" },

  // 6.1 - PARCELAMENTO TRIBUTOS
  "PARCELAMENTO DE IRRF": { subcategory: "6.1.1 - PARCELAMENTO TRIBUTOS", category: "6.1 - PARCELAMENTO TRIBUTOS" },
  "PARCELAMENTO DE ICMS": { subcategory: "6.1.1 - PARCELAMENTO TRIBUTOS", category: "6.1 - PARCELAMENTO TRIBUTOS" },
  "PARCELAMENTO FEDERAL": { subcategory: "6.1.1 - PARCELAMENTO TRIBUTOS", category: "6.1 - PARCELAMENTO TRIBUTOS" },
  "PARCELAMENTO DE INSS": { subcategory: "6.1.1 - PARCELAMENTO TRIBUTOS", category: "6.1 - PARCELAMENTO TRIBUTOS" },

  // 7.1 - RESERVA
  "ADIANTAMENTO P/DIRETORES": { subcategory: "7.1.1 - RESERVA", category: "7.1 - RESERVA" },
  "ANTECIPAÇÃO DE DISTRIBUIÇÃO DE LUCROS": { subcategory: "7.1.1 - RESERVA", category: "7.1 - RESERVA" },
  "SOCIO 1": { subcategory: "7.1.1 - RESERVA", category: "7.1 - RESERVA" },

  // EXCLUSIONS (Á DEFINIR / SEM CLASSIFICAÇÃO)
  "DESPESAS C/ REFEIÇÕES E LANCHES - ADMINISTRATIVOS": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "OBRAS E INSTALAÇÕES EM ANDAMENTO": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "GRATIFICAÇÃO": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "DESPESAS DE AMBULATORIO": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "VIAGENS E ESTADIAS ADMINISTRATIVAS": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "SEGUROS A PAGAR": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "Rendimento aplicac. financeira": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "DESPESAS SITE": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "VARIAÇÃO MONETÁRIA PASSIVAS": { subcategory: "Á DEFINIR", category: "Á DEFINIR" },
  "RENDIMENTOS S/APLICAÇÕES FINANCEIRAS": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "APLICAÇÃO BANCO SANTANDER": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "TARIFA DE COBRANÇA": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "EMPRÉSTIMOS - ENTRADA": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "MATERIAL DE LIMPEZA - FROTA": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "FORNECEDORES DIVERSOS NACIONAIS": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "CLIENTES DIVERSOS NACIONAIS": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
  "APLICAÇÃO BRADESCO 27899-8": { subcategory: "SEM CLASSIFICAÇÃO", category: "SEM CLASSIFICAÇÃO" },
};
